name: scsim_ext_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>3.7.0,!=3.8.0
  - numpy
  - matplotlib
  - scanpy>=1.7.0
  - anndata
  - pandas>=1.1.0
  - scipy>=1.6.0
  - ipykernel
  - pip # for pip installing scsim_ext
  - git # for pip installing scsim_ext from github
  - pip:
     - git+https://github.com/nitzanlab/scsim-ext.git